<a href="https://colab.research.google.com/github/Varanasi-Software-Junction/vsjcolab/blob/main/starting_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imports**

In [48]:
import numpy as np

Create an array using list

In [49]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Create an array using tuple

In [50]:
a = np.array((1, 2, 3, 4, 5))
print(a)

[1 2 3 4 5]


Create an array using set

In [51]:
a = np.array({1,2,3,4,5})
print(a)


{1, 2, 3, 4, 5}


Create an array using dictionary

In [52]:
a = np.array({"one":1,"two":2,"three":3,"four":4,"five":5})
print(a)


{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}


Create an array using range

In [53]:
a = np.array(range(1,6))
print(a)


[1 2 3 4 5]


Create an array using ones

In [54]:
a = np.ones(5)
print(a)


[1. 1. 1. 1. 1.]


Create an array using zeros

In [55]:
a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


Create an array using arange

In [56]:
a = np.arange(5)
print(a)
a = np.arange(1,6)
print(a)
a = np.arange(1,6,2)
print(a)
a = np.arange(5,0,-1)
print(a)


[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


Create an array using random

In [57]:
a = np.random.rand(1,10)
print(a)

a =np.random.power(5, 5)
print(a)

a =np.random.randint(5,size= 5)
print(a)

rng = np.random.default_rng()
a =rng.integers(5,size=5)
print(a)


[[0.67121009 0.2980289  0.12356092 0.30055242 0.98518739 0.14157377
  0.21406213 0.70181604 0.69759184 0.18417412]]
[0.82039814 0.881792   0.65365518 0.26894867 0.95711875]
[4 3 0 3 1]
[0 0 2 3 0]
